name: ci-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.2-alpine
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: root
          POSTGRES_DB: cookinator
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.3"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install golang goose
        run: |
          curl -fsSL https://raw.githubusercontent.com/pressly/goose/master/install.sh | sh
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
