// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Family struct {
	ID              uuid.UUID
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	Name            string
	CreatedByUserID uuid.UUID
}

type Ingredient struct {
	ID      int32
	Name    string
	Density pgtype.Numeric
}

type Recipe struct {
	ID             uuid.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	Name           string
	CookingProcess string
	FamilyID       uuid.UUID
	Items          []byte
}

type User struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	FirstName string
	Email     string
	Password  string
	FamilyID  uuid.UUID
}
