// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Family struct {
	ID              pgtype.UUID
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	Name            string
	CreatedByUserID pgtype.UUID
}

type Ingredient struct {
	ID      int32
	Name    string
	Density pgtype.Numeric
}

type Recipe struct {
	ID             pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	Name           string
	CookingProcess string
	FamilyID       pgtype.UUID
	Items          []byte
}

type User struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	FirstName string
	Email     string
	Password  string
	FamilyID  pgtype.UUID
}
