// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Family struct {
	ID              uuid.UUID        `json:"id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	Name            string           `json:"name"`
	CreatedByUserID uuid.UUID        `json:"created_by_user_id"`
}

type Ingredient struct {
	ID      int32          `json:"id"`
	Name    string         `json:"name"`
	Density pgtype.Numeric `json:"density"`
}

type Recipe struct {
	ID             uuid.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	Name           string           `json:"name"`
	CookingProcess string           `json:"cooking_process"`
	FamilyID       uuid.UUID        `json:"family_id"`
	Items          []byte           `json:"items"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	FirstName string           `json:"first_name"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	FamilyID  uuid.UUID        `json:"family_id"`
}
